########################################## DEVELOP ##########################################
stages:
  - sonar
  - build
  - deploy

sonarqube-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  stage: sonar
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - echo ${SONAR_HOST_URL}
    - sonar-scanner
  tags:
    - vmogroup
  allow_failure: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "production" || $CI_COMMIT_BRANCH == "uat"'

.base-build: &build-template
  stage: build
  image: docker
  services:
    - name: docker:24.0.6-dind-alpine3.18
      entrypoint:
        - dockerd-entrypoint.sh
        - --tls=false
  script:
    - |
      mkdir -p config secrets
      cat ${ENV} > config/default.yaml
      cat ${GOOGLE_CERTS} > secrets/google-certs.json
      docker login -u "$CI_REGISTRY_USER" -p $CI_JOB_TOKEN $CI_REGISTRY
      docker build -t registry.git.vmo.dev/vus/fc24021/backend/be-cms:$CI_ENVIRONMENT_NAME-$CI_COMMIT_SHORT_SHA .
      docker push registry.git.vmo.dev/vus/fc24021/backend/be-cms:$CI_ENVIRONMENT_NAME-$CI_COMMIT_SHORT_SHA

.base-deploy: &deploy-template
  stage: deploy
  image: docker:24.0.6-dind-alpine3.18
  script:
    - |
      export CONTAINER_ID=$(docker ps -aq --filter "name=be-cms" | grep .)
      if [ ! -z "$CONTAINER_ID" ]; then \
        docker stop "$CONTAINER_ID" && docker container prune -f; \
      else \
        echo "No be-cms container is running"; \
      fi;
      docker run \
        -dit -p 3002:3002 -m 3g \
        --restart=always --name be-cms \
        registry.git.vmo.dev/vus/fc24021/backend/be-cms:$CI_ENVIRONMENT_NAME-$CI_COMMIT_SHORT_SHA

dev-build:
  <<: *build-template
  environment:
    name: dev
  tags:
    - fancho-dev
  only:
    - develop
    - feat/cicd

dev-deploy:
  <<: *deploy-template
  environment:
    name: dev
  tags:
    - fancho-dev
  only:
    - develop
    - feat/cicd

uat-build:
  <<: *build-template
  environment:
    name: uat
  tags:
    - fancho-uat
  only:
    - uat

uat-deploy:
  <<: *deploy-template
  environment:
    name: uat
  tags:
    - fancho-uat
  only:
    - uat
